FROM node:22-alpine as build

WORKDIR /app

COPY  package*.json /app/
RUN npm install

COPY . .

RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=build /app/package*.json ./
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

CMD [ "npm" , "run", "start:prod" ]